/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pacoportela.elco.descuentosnuevo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URL;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Paco Portela Henche
 * @date Octubre 2024
 */
public class Interfaz extends javax.swing.JFrame {
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        try {
            this.cargarIvas();
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        String s = this.bgIvas.getSelection().getActionCommand();
        double i = Double.parseDouble(s);
        this.etInfo.setText("IVA " + String.valueOf(i) + "%");
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int p = d.width - this.getWidth();
        this.setLocation(p, 0);
        ponerIcono();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgIvas = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        etTipo = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        etPersonal = new javax.swing.JLabel();
        tfPersonal = new javax.swing.JTextField();
        etPrecio = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        etDto = new javax.swing.JLabel();
        tfDto = new javax.swing.JTextField();
        etUds = new javax.swing.JLabel();
        tfUds = new javax.swing.JTextField();
        etDtoUds = new javax.swing.JLabel();
        tfDtoUds = new javax.swing.JTextField();
        etFinal = new javax.swing.JLabel();
        etPrecioFinal = new javax.swing.JLabel();
        btBorrar = new javax.swing.JButton();
        etInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFichero = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        menuCambiar = new javax.swing.JMenu();
        miCambiar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        etTipo.setText("Tipo IVA");

        bgIvas.add(rb1);
        rb1.setText("IVA 4%");
        rb1.setActionCommand("4");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActionPerformed(evt);
            }
        });

        bgIvas.add(rb2);
        rb2.setText("IVA 10%");
        rb2.setActionCommand("10");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActionPerformed(evt);
            }
        });

        bgIvas.add(rb3);
        rb3.setSelected(true);
        rb3.setText("IVA 21%");
        rb3.setActionCommand("21");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActionPerformed(evt);
            }
        });

        bgIvas.add(rb4);
        rb4.setText("IVA 0%");
        rb4.setActionCommand("0");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActionPerformed(evt);
            }
        });

        etPersonal.setText("IVA personal");

        tfPersonal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPersonalKeyPressed(evt);
            }
        });

        etPrecio.setText("Precio");

        tfPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFocusGained(evt);
            }
        });
        tfPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPrecioKeyPressed(evt);
            }
        });

        etDto.setText("Dto. %");

        tfDto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFocusGained(evt);
            }
        });
        tfDto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDtoKeyPressed(evt);
            }
        });

        etUds.setText("Unidades");

        tfUds.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUds.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFocusGained(evt);
            }
        });
        tfUds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUdsKeyPressed(evt);
            }
        });

        etDtoUds.setText("Dto. Uds.");

        tfDtoUds.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDtoUds.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFocusGained(evt);
            }
        });
        tfDtoUds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDtoUdsKeyPressed(evt);
            }
        });

        etFinal.setText("Precio Final");

        etPrecioFinal.setBackground(new java.awt.Color(255, 255, 0));
        etPrecioFinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etPrecioFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etPrecioFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        etPrecioFinal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etPrecioFinal.setOpaque(true);

        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        etInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etInfo.setText("IVA: 21.0");

        menuFichero.setText("Fichero");

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        menuFichero.add(miSalir);

        jMenuBar1.add(menuFichero);

        menuCambiar.setText("Cambiar Ivas");

        miCambiar.setText("Cambiar");
        miCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCambiarActionPerformed(evt);
            }
        });
        menuCambiar.add(miCambiar);

        jMenuBar1.add(menuCambiar);

        menuAyuda.setText("Ayuda");

        jMenuItem2.setText("Ayuda");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAyudaActionPerformed(evt);
            }
        });
        menuAyuda.add(jMenuItem2);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etPersonal)
                            .addComponent(etTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etDto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etUds)
                            .addComponent(etDtoUds))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etPrecioFinal)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfDtoUds, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfUds, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etFinal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(etTipo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etPersonal))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etPrecio)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etDto)
                    .addComponent(tfDto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etUds)
                    .addComponent(tfUds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etDtoUds)
                    .addComponent(tfDtoUds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etFinal)
                    .addComponent(etPrecioFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBorrar)
                    .addComponent(etInfo))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String s = evt.paramString();
        System.out.println(s);
        this.tfPrecio.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void tfPersonalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPersonalKeyPressed

        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            this.obtenerIva(new java.awt.event.ActionEvent(new Object(), 0, ""));
            this.calcularPrecioFinal();
            this.tfPrecio.requestFocusInWindow();
        }
    }//GEN-LAST:event_tfPersonalKeyPressed

    private void tfPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecioKeyPressed
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            this.calcularPrecioFinal();
            this.tfDto.requestFocusInWindow();
        }
    }//GEN-LAST:event_tfPrecioKeyPressed

    private void tfDtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDtoKeyPressed
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            this.calcularPrecioFinal();
            this.tfUds.requestFocusInWindow();
        }
    }//GEN-LAST:event_tfDtoKeyPressed

    private void tfUdsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUdsKeyPressed
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            this.calcularPrecioFinal();
            this.tfDtoUds.requestFocusInWindow();
        }
    }//GEN-LAST:event_tfUdsKeyPressed

    private void tfDtoUdsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDtoUdsKeyPressed
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            this.calcularPrecioFinal();
            this.tfPrecio.requestFocusInWindow();
        }
    }//GEN-LAST:event_tfDtoUdsKeyPressed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        String s = evt.getActionCommand();
        System.out.println(s);
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActionPerformed
        this.obtenerIva(evt);
        this.calcularPrecioFinal();
        this.tfPrecio.requestFocusInWindow();
    }//GEN-LAST:event_rbActionPerformed

    private void miCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCambiarActionPerformed
        String a = evt.getActionCommand();
        System.out.println(a);
        String s = JOptionPane.showInputDialog
        (this, "Introduzca los nuevos ivas de esta forma: 4/8/10/22",
                "4/8/10/22");
        if(s == null) return;
        String[] nuevosIvas = s.split("/");
        for(int i = 0; i < nuevosIvas.length; i++){
            switch(i){
                case 0 -> {
                    this.rb1.setActionCommand(nuevosIvas[i]);
                    this.rb1.setText("IVA " + nuevosIvas[i] + "%");
                }
                case 1 -> {
                    this.rb2.setActionCommand(nuevosIvas[i]);
                    this.rb2.setText("IVA " + nuevosIvas[i] + "%");
                }
                case 2 -> {
                    this.rb3.setActionCommand(nuevosIvas[i]);
                    this.rb3.setText("IVA " + nuevosIvas[i] + "%");
                }
                case 3 -> {
                    this.rb4.setActionCommand(nuevosIvas[i]);
                    this.rb4.setText("IVA " + nuevosIvas[i] + "%");
                }
                default -> {
                }
            }
        }
        try {
            this.grabarIvas();
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miCambiarActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        String s = evt.getActionCommand();
        System.out.println(s);
        this.tfPrecio.setText("");
        this.tfDto.setText("");
        this.tfUds.setText("");
        this.tfDtoUds.setText("");
        this.etPrecioFinal.setText("");
        this.tfPrecio.requestFocusInWindow();
    }//GEN-LAST:event_btBorrarActionPerformed

    private void tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFocusGained
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();
    }//GEN-LAST:event_tfFocusGained

    private void miAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAyudaActionPerformed
        String s = evt.getActionCommand();
        System.out.println(s);
        String mensaje = """
                         Para realizar descuentos en cadena
                         escribalos separados por la barra '/'
                         de esta forma 25/12.5/2.5""";
        JOptionPane.showMessageDialog(this, mensaje, "Ayuda",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_miAyudaActionPerformed
 
    private void cargarIvas() throws Exception{
        String s = Files.readString(Paths.get("Ivas.txt"));
        String[] nuevosIvas = s.split("/");
        for(int i = 0; i < nuevosIvas.length; i++){
            switch(i){
                case 0 -> {
                    this.rb1.setActionCommand(nuevosIvas[i]);
                    this.rb1.setText("IVA " + nuevosIvas[i] + "%");
                }
                case 1 -> {
                    this.rb2.setActionCommand(nuevosIvas[i]);
                    this.rb2.setText("IVA " + nuevosIvas[i] + "%");
                }
                case 2 -> {
                    this.rb3.setActionCommand(nuevosIvas[i]);
                    this.rb3.setText("IVA " + nuevosIvas[i] + "%");
                }
                case 3 -> {
                    this.rb4.setActionCommand(nuevosIvas[i]);
                    this.rb4.setText("IVA " + nuevosIvas[i] + "%");
                }
                default -> {
                }
            }
        }
    }
    
    private void ponerIcono(){
    URL url = Interfaz.class.getResource("/Descuento.jpg");
        if(url != null){
            ImageIcon icono = new ImageIcon(url);
            this.setIconImage(icono.getImage());
        }
    }
    private void calcularPrecioFinal(){
        double coste = 0.0;
        try{
            coste = Double.parseDouble(this.tfPrecio.getText());
        }
        catch(NumberFormatException ex){
            coste = 0.0;
            this.tfPrecio.setText("");
            this.etPrecioFinal.setText("");
        }
        if(coste == 0.0) return;
        double[] descuentos = this.getDescuentos();
        if(descuentos == null) this.tfDto.setText("");
        int unidades = 0;
        try{
            unidades = Integer.parseInt(this.tfUds.getText());
        }
        catch(NumberFormatException ex){
            unidades = 0;
            this.tfUds.setText("");
        }
        int dtoUds = 0;
        try{
            dtoUds = Integer.parseInt(this.tfDtoUds.getText());
        }
        catch(NumberFormatException ex){
            dtoUds = 0;
            this.tfDtoUds.setText("");
        }
        if(descuentos != null && descuentos.length > 0){
            for(int i = 0; i < descuentos.length; i++){
                coste = coste - (coste * descuentos[i] / 100);
            }
        }
        if(unidades != 0 && dtoUds != 0){
            coste = coste * unidades / (unidades + dtoUds);
        }
        coste = coste * (1 + this.iva / 100);
        DecimalFormat formato = new DecimalFormat("###,##0.###");
        this.etPrecioFinal.setText(formato.format(coste));
    }
    
    private void obtenerIva(java.awt.event.ActionEvent evt){
        this.iva = 1000;
        if(this.tfPersonal.getText().length() > 0){
            try{
                this.iva = Double.parseDouble(this.tfPersonal.getText());
            }
            catch(NumberFormatException ex){
                this.iva = 1000;
            }
        }
        if(this.iva == 1000){
            String s = evt.getActionCommand();
            if(s.length() > 0){
                this.iva = Double.parseDouble(evt.getActionCommand());
            }
            else{
                this.iva = 
                        Double.parseDouble
                        (this.bgIvas.getSelection().getActionCommand());
            }
        }
        this.etInfo.setText("IVA " + iva + "%");
    }
   
    private double[] getDescuentos(){
        String[] tokens = this.tfDto.getText().split("/");
        if(tokens.length == 0) return null;
        double[] descuentos = new double[tokens.length];
        for(int i = 0; i < tokens.length; i++){
            try{
                descuentos[i] = Double.parseDouble(tokens[i]);
            }
            catch(NumberFormatException ex){
                descuentos = null;
                break;
            }
        }
        return descuentos;
    }
    
    private void grabarIvas()throws Exception {
        String ivas = this.rb1.getActionCommand() + "/" +
                this.rb2.getActionCommand() + "/" +
                this.rb3.getActionCommand() + "/" +
                this.rb4.getActionCommand();
        Files.writeString(Paths.get("Ivas.txt"),
                ivas,
                Charset.forName("UTF-8"),
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING);
    }


    private double iva = 21.0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgIvas;
    private javax.swing.JButton btBorrar;
    private javax.swing.JLabel etDto;
    private javax.swing.JLabel etDtoUds;
    private javax.swing.JLabel etFinal;
    private javax.swing.JLabel etInfo;
    private javax.swing.JLabel etPersonal;
    private javax.swing.JLabel etPrecio;
    private javax.swing.JLabel etPrecioFinal;
    private javax.swing.JLabel etTipo;
    private javax.swing.JLabel etUds;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCambiar;
    private javax.swing.JMenu menuFichero;
    private javax.swing.JMenuItem miCambiar;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JTextField tfDto;
    private javax.swing.JTextField tfDtoUds;
    private javax.swing.JTextField tfPersonal;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfUds;
    // End of variables declaration//GEN-END:variables
}
